### PR TITLE
grunt + some care

### PR DESCRIPTION
**Pull request by cfoellmann**

### CODE REVIEW

**Comment by yoren** [comment]
Cool. You did a great job Chris.

**Comment by cfoellmann** [comment]
I want to revive the WPCollab project. One little step at a time.

**Comment by yoren** [comment]
Count me in. I'll do the zh_TW translation this weekend.

**Comment by cfoellmann** [comment]
Should put the project on transifex/ www.wp-translations.org?
Can be automated via grunt.

**Comment by yoren** [comment]
I'm ok with it, it looks nice, we'll need to submit Hello Emoji to the site, right?

**Comment by cfoellmann** [comment]
It is up.https://www.transifex.com/projects/p/hello-emoji/ - transfer is started and more languages will be available as soon as it has moved to WP-Translations

**Comment by yoren** [comment]
Just registered an account and sent you an adding language request.

**Pull request merged**
